CREATE DATABASE DBFirst

USE DBFirst
GO

CREATE TABLE CATEGORY
(
	CategoryID int IDENTITY(1,1),
	CategoryName Nvarchar(50) NOT NULL,
	CONSTRAINT PK_CATEROGY PRIMARY KEY(CategoryID)
)
GO
CREATE TABLE ITEM
(
	ItemID int IDENTITY(1,1),
	ItemName Nvarchar(50) NOT NULL,
	ItemPrice money NOT NULL,
	ItemImageName Nvarchar(50),
	CategoryID int ,
	CONSTRAINT PK_ITEM PRIMARY KEY(ItemID),
	CONSTRAINT FK_ITEM_CATEGORY FOREIGN KEY(CategoryID)
	REFERENCES CATEGORY (CategoryID) ON DELETE SET NULL,
)
Go
INSERT INTO CATEGORY(CategoryName) VALUES ('CHO')
INSERT INTO CATEGORY(CategoryName) VALUES ('DE')
INSERT INTO CATEGORY(CategoryName) VALUES ('MEO')

INSERT INTO ITEM(ItemName,ItemPrice,ItemImageName,CategoryID) VALUES ('CHO ALASKA',21000000,'IMGCHO',1)
INSERT INTO ITEM(ItemName,ItemPrice,ItemImageName,CategoryID) VALUES ('DE TAY TANG',30000000,'IMGDE',2)
INSERT INTO ITEM(ItemName,ItemPrice,ItemImageName,CategoryID) VALUES ('MEO DIAHIA',50000000,'IMGMEO',3)


